name: Bad At Socialism
favicon: null
layout_spectrum: 0.32041202019900084
typography_spectrum: 0.4301346531137824
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.9775912682525814
  lightness: 0.22007811348885298
  saturation: 0.7034449379425496
  rhythmicContrast: 0.7833296537864953
purpose: []
